version: "3"

volumes:
  gnonode: {}
  faucet: {}

networks:
  gnochess:
    enable_ipv6: false

services:
  gnoland:
    build: .
    image: ghcr.io/gnolang/gnochess:latest
    environment:
      - LOG_LEVEL=4
    ports:
      - "26657:26657"
    restart: on-failure
    working_dir: /opt/gno/src/gno.land
    command: gnoland start
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    networks:
      gnochess:
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "100m"

  gnoweb:
    build: .
    image: ghcr.io/gnolang/gnochess:latest
    working_dir: /opt/gno/src/gno.land
    command: gnoweb -bind 0.0.0.0:8888 -remote gnoland:26657
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - "8888:8888"
    restart: on-failure
    networks:
      gnochess:
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "100m"

  web:
    build: ./web
    image: ghcr.io/gnolang/gnochess/web:latest
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - "1313:1313"
    restart: on-failure
    networks:
      gnochess:
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "100m"
    volumes:
      - ./web:/app
    environment:
      VITE_GNO_WS_URL: "http://localhost:26657/websocket"
      VITE_GNO_JSONRPC_URL: "http://localhost:26657"
      VITE_GNO_CHESS_REALM: "gno.land/r/demo/chess1"
      VITE_FAUCET_URL: "http://localhost:5050"

  redis:
    image: "redis:7.2"
    networks:
      gnochess:
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - "6379:6379"

  faucet:
    image: golang:1.20
    depends_on:
      - "redis"
      - "gnoland"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    command:
      - "go"
      - "run"
      - "."
      - "--remote"
      - "http://gnoland:26657"
      - "--listen-address"
      - "0.0.0.0:5050"
      - "--mnemonic"
      - "source bonus chronic canvas draft south burst lottery vacant surface solve popular case indicate oppose farm nothing bullet exhibit title speed wink action roast" # test1
      - "--redis-url"
      - "redis://redis:6379"
    working_dir: "/app"
    volumes:
      - "faucet:/go"
      - "./faucet:/app"
    ports:
      - "5050:5050"
    networks:
      gnochess:

  signup-web:
    image: node
    command: ["yarn", "run", "dev", "--host=0.0.0.0", "--port=8080"]
    working_dir: "/app"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - "./signup:/app"
    ports:
      - "8080:8080"
    environment:
      VITE_API_BASE_URL: "localhost:8080"
      VITE_NETLIFY_FUNCTIONS_URL: "http://localhost:9000"
    networks:
      gnochess:

  signup-functions:
    image: williamjackson/netlify-cli
    stop_grace_period: 500ms # XXX: improve by making this a dockerfile which has dumb-init
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    depends_on:
      - redis
    command: ["functions:serve", "-f", "./functions", "-p", "9000"]
    working_dir: "/app"
    volumes:
      - "./signup:/app"
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: "development"
      REDIS_URL: "redis://redis:6379"
    networks:
      gnochess:
