name: realm

on:
  push:
    paths:
      - "r/**"
    branches:
      - main

env:
  GNOKEY: "go run github.com/gnolang/gno/gno.land/cmd/gnokey"
  GNOCHESS_REALM: gno.land/r/demo/chess_${GITHUB_SHA}
  GNOLAND_REMOTE_CHAIN: "https://rpc.gnochess.com:443"
  MNEMONIC: "source bonus chronic canvas draft south burst lottery vacant surface solve popular case indicate oppose farm nothing bullet exhibit title speed wink action roast"

jobs:
  deploy-realm:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"
      - run: go mod download -x
      - run: |
          printf '\n\n%s\n\n' "$MNEMONIC" | $GNOKEY add --recover --insecure-password-stdin test1'
          echo "" | $GNOKEY maketx addpkg \
          --gas-wanted 50000000 \
          --gas-fee 1ugnot \
          --pkgpath gno.land/r/demo/chess_${GITHUB_SHA} \
          --pkgdir r/chess \
          --insecure-password-stdin \
          --remote  \
          --broadcast test1'

          echo "" | $GNOKEY maketx addpkg \
          --gas-wanted 50000000 \
          --gas-fee 1ugnot \
          --pkgpath gno.land/r/demo/reward_entry_${GITHUB_SHA} \
          --pkgdir r/reward_entry \
          --insecure-password-stdin \
          --remote  \
          --broadcast test1'
