name: integration

on:
  pull_request:
    paths:
      - "testdata/**"
      - "go.sum"
  push:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - run: 	go test -v -run='TestIntegration/.*' .
