name: realm

on:
  pull_request:
    paths:
      - "realm/**"
      - "Makefile"
      - "go.sum"
  push:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - name: install gno
        run: go install github.com/gnolang/gno/gnovm/cmd/gno
      - name: gno test
        run: gno test --verbose ./realm
